configs:
  # mmdet: "configs/mmdet/yolox.yaml"
  mmyolo: "configs/mmyolo/yolov8.yaml"
  mmpose: "configs/mmpose/hrnet.yaml"
  unitrack: "configs/unitrack/detco.yaml"
th_bbox: 0.2
th_iou: 0.95
th_delete: 0.3 # threshold of confidence score of keypoints
th_diff: 20  # threshold of difference for finding same keypoints
th_count: 5
