common:
    # Model related
    model_type: detco
    remove_layers: ['layer4']
    im_mean: [0.4914, 0.4822, 0.4465]
    im_std: [0.2023, 0.1994, 0.2010]
    nopadding: False
    head_depth: -1
    resume: 'models/unitrack/detco.pth'

    # Misc
    down_factor: 8
    infer2D: True
    workers: 4
    device: cuda

posetrack:
    obid: 'lighttrack_MSRA152'
    data_root: '/home/wangzd/datasets/GOT/Posetrack2018'
    split: 'val'
    track_buffer: 300
    nms_thres: 0.4
    conf_thres: 0.5
    iou_thres: 0.5
    frame_rate: 30
    save_videos: False
    save_images: False
    prop_flag: False
    feat_size: [4,10]
    max_mask_area: 400
    dup_iou_thres: 0.2
    confirm_iou_thres: 0.6
    first_stage_thres: 0.7
    use_kalman: True
    asso_with_motion: True
    motion_lambda: 0.9999
    motion_gated: False
    only_position: True
