# config: "submodules/mmdet/configs/yolox/yolox_x_8x8_300e_coco.py"
# weights: "https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth"
config: submodules/mmdet/configs/yolox/yolox_x_8xb8-300e_coco.py
weights: https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth
